### PR TITLE
Change mailx -a to -A for ubuntu  18+

### PR DESCRIPTION
**Pull request by kjeldflarup**
Solves #5

### CODE REVIEW

**Comment by bwachter** [comment]
This will break on non-Ubuntu. What's the output of mailx -V there? Heirloom mailx reports something like "12.5 7/5/10" - if the format of whatever is on Ubuntu is different that could be used to switch variants.

Other option would be the help text - heirloom doesn't have a help options, but prints usage information for invalid. That could also be used.

Third option would be to add a config flag for selecting the mailx version. If that makes sense depends on how compatible the Ubuntu one is to heirloom - if there's risk of additional breakage we probably shouldn't select a potentially broken one, if that flag is the only incompatibility it's probably better to automatically select.

**Comment by bwachter** [comment]
@kjeldflarup Could you please respond to my questions? I do not have an Ubuntu system available. While I'm happy to have this compatible with Ubuntu as well those changes must not break usage with heirloom mailx (the version this was written for) I'm unable to do so without responsive Ubuntu users capable of testing changes there.

**Comment by kjeldflarup** [comment]
I was trying to figure out, when the change in mailx happened. It seems necessary to check the version of mailx to make it run on all systems.

**Comment by pkropf** [comment]
I've access to some Ubuntu systems and can help with this.

> peter@helpdesk:~$ cat /etc/issue
> Ubuntu 18.04.5 LTS \n \l
> 
> peter@helpdesk:~$ mailx -V
> mailx (GNU Mailutils) 3.4
> Copyright (C) 2007-2017 Free Software Foundation, inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>
> peter@helpdesk:~$ 


> peter@b-smtp:~$ cat /etc/issue
> Ubuntu 20.04.2 LTS \n \l
> 
> peter@b-smtp:~$ mailx -V
> mailx (GNU Mailutils) 3.7
> Copyright (C) 2007-2019 Free Software Foundation, inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> peter@b-smtp:~$ 


> peter@prime:~$ cat /etc/issue
> Ubuntu 21.04 \n \l
> 
> peter@prime:~$ mailx -V
> mailx (GNU Mailutils) 3.11.1
> Copyright (C) 2007-2021 Free Software Foundation, inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> peter@prime:~$

**Comment by bwachter** [comment]
@pkropf I just pushed a change that uses the version output from your comment to distinguish between mailx variants to master. I've verified that it doesn't break on a Heirloom system - can you check if it makes it work on Ubuntu?

**Comment by bwachter** [comment]
I assume this has been fixed with 72f57150c647e26993cd3f4558e7974e474be209

**Pull request closed without merging**
